version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code
hooks:
  BeforeInstall:
    - location: scripts/apache_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/apache2_start.sh
      timeout: 300
      runas: root
